apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: argo-svc
  name: argo-svc
spec:
  ports:
    - name: 5000-80
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: argo-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
